apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-v1-ingress
  namespace: webapp-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: ca-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
    - host: webapp1.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-v1-service
                port:
                  number: 80
    - host: webapp2.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-v2-service
                port:
                  number: 80
  tls:
    - hosts:
        - webapp1.example.local
        - webapp2.example.local
      secretName: ingress-cert
